// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONoQBRgOUP93gZtJIDA9MEU8PRsZ9SBk',
    appId: '1:780373644453:web:3570111dfc7c091d49694c',
    messagingSenderId: '780373644453',
    projectId: 'finals-24947',
    authDomain: 'finals-24947.firebaseapp.com',
    storageBucket: 'finals-24947.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgbS-wIwkFVZxn6Ctx-OjEErcZ8KHzXs',
    appId: '1:780373644453:android:6a1138769a33879649694c',
    messagingSenderId: '780373644453',
    projectId: 'finals-24947',
    storageBucket: 'finals-24947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBS0c5rt33_L-h2GkAeMdyBg6gV9VDUdw',
    appId: '1:780373644453:ios:879b2b5e76d989e449694c',
    messagingSenderId: '780373644453',
    projectId: 'finals-24947',
    storageBucket: 'finals-24947.appspot.com',
    iosClientId: '780373644453-d6k61o924gs0aqt8ij4702jheek806ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDONoQBRgOUP93gZtJIDA9MEU8PRsZ9SBk',
    appId: '1:780373644453:web:06083b39a96dd6f449694c',
    messagingSenderId: '780373644453',
    projectId: 'finals-24947',
    authDomain: 'finals-24947.firebaseapp.com',
    storageBucket: 'finals-24947.appspot.com',
  );
}